trainer:
  env_id: 'LunarLander-v3'
  seed: 42
  max_steps: 100000

  eval_every: 50
  eval_episodes: 2
  render_eval: false 
  
  # checkpoint 
  ckpt_dir: rl_Lab/checkpoints
  ckpt_every: 20000
  resume: true

  # logging
  log_dir: rl_Lab/logs
  log_every: 10000

eval:
  render_eval: true
  eval_episodes: 10
  





