# configs/dqn.yaml
gamma: 0.99
lr: 0.01
batch_size: 512
buffer_size: 50000
warmup_steps: 1000
min_replay_size: 1000
train_every: 1
target_update_every: 5000
eps_start: 1.0
eps_end: 0.01
eps_decay_steps: 20000
eps_min: 0.05
eps_decay: 0.9995
seed: 42
epsilon: 0.1 # Exploration
max_norm: 10
