# configs/dqn.yaml
gamma: 0.99
lr: 0.0005
batch_size: 128
buffer_size: 50000
warmup_steps: 1000
min_replay_size: 1000
train_every: 1
target_update_every: 1000
eps_start: 1.0
eps_end: 0.05
eps_decay_steps: 20000
seed: 42
epsilon: 0.1 # Exploration
